[package]
name = "endless_launcher"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
slint = "1.3.0"

[build-dependencies]
slint-build = "1.3.0"
